# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-10 17:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nicheng', models.CharField(default='小小阳同学', max_length=20, verbose_name='昵称')),
                ('zhiye', models.CharField(default='coder', max_length=20, verbose_name='职业')),
                ('xianju', models.CharField(max_length=20, verbose_name='现居地')),
                ('img', models.ImageField(default='img/bubble.png', upload_to='', verbose_name='用户头像')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除此用户')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('brief', models.CharField(max_length=200, verbose_name='简介')),
                ('text', mdeditor.fields.MDTextField(verbose_name='正文')),
                ('image', models.ImageField(upload_to='', verbose_name='预览图')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 3, 10, 17, 14, 46, 515804, tzinfo=utc), verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('is_tag', models.BooleanField(default=False, verbose_name='是否推荐&置顶')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('like_it', models.IntegerField(default=0, verbose_name='访问量')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞数')),
                ('pingl', models.IntegerField(default=0, verbose_name='评论量')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 3, 11, 1, 14, 46, 517558), verbose_name='创建时间')),
                ('target_user_id', models.IntegerField(verbose_name='从用户')),
                ('relation', models.IntegerField(default=0, verbose_name='状态')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='主用户')),
            ],
            options={
                'verbose_name_plural': '用户关注',
                'verbose_name': '用户关注',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分类')),
                ('splendid', models.BooleanField(default=False, verbose_name='是否将此类在首页展示')),
                ('shuoming', models.CharField(default='可能，你觉得自己没有足够得优秀，但我始终相信你仍然在努力坚持着!', max_length=128, verbose_name='分类说明')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('pcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sj', to='bolg.Catalog', verbose_name='上级分类')),
            ],
            options={
                'verbose_name_plural': '博客分类',
                'verbose_name': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='评论正文')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 3, 10, 17, 14, 46, 517009, tzinfo=utc), verbose_name='创建时间')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolg.Article', verbose_name='文章id')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolg.Comment', verbose_name='上级评论')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '文章评论',
                'verbose_name': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='LBTImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='轮播图')),
                ('title', models.CharField(default='站长很忙没写描述啊,有意见来打我呀', max_length=20, verbose_name='描述')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '首页轮播图',
                'verbose_name': '首页轮播图',
            },
        ),
        migrations.CreateModel(
            name='Liek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 3, 11, 1, 14, 46, 518609), verbose_name='点赞时间')),
                ('relation', models.IntegerField(verbose_name='对文章状态')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolg.Article', verbose_name='文章id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '点赞',
                'verbose_name': '点赞',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标签名字')),
            ],
            options={
                'verbose_name_plural': '博客标签',
                'verbose_name': '博客标签',
            },
        ),
        migrations.CreateModel(
            name='TagZJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolg.Article', verbose_name='文章id')),
                ('tags_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolg.Tags', verbose_name='标签id')),
            ],
            options={
                'verbose_name_plural': '标签中间表',
                'verbose_name': '标签中间表',
            },
        ),
        migrations.CreateModel(
            name='Wailian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hear', models.CharField(max_length=128, verbose_name='连接地址不需要http://')),
                ('name', models.CharField(max_length=128, verbose_name='外联名字')),
            ],
            options={
                'verbose_name_plural': '为您推荐',
                'verbose_name': '为您推荐',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolg.Catalog', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
