# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-19 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190619_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_it',
            field=models.IntegerField(default=0, verbose_name='访问量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 1, 57, 36, 758063), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 1, 57, 36, 758104), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 1, 57, 36, 764510), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 1, 57, 36, 763752), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liek',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 1, 57, 36, 770237), verbose_name='点赞时间'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=128, verbose_name='标签名字'),
        ),
    ]
