# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-27 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190620_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbtimg',
            name='title',
            field=models.CharField(default='站长很忙没写描述啊,有意见来打我呀', max_length=20, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 17, 1, 38, 244941), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 17, 1, 38, 245065), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 17, 1, 38, 251414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 17, 1, 38, 250703), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liek',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 17, 1, 38, 252780), verbose_name='点赞时间'),
        ),
    ]
