# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-27 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190627_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pingl',
            field=models.IntegerField(default=1, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='article',
            name='zan',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 9, 9, 113440), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 9, 9, 113472), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 9, 9, 117402), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 9, 9, 116660), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liek',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 9, 9, 119898), verbose_name='点赞时间'),
        ),
    ]
