# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-28 03:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190627_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 11, 16, 10, 583234), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 11, 16, 10, 583265), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 11, 16, 10, 586543), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 11, 16, 10, 585881), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liek',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 11, 16, 10, 588092), verbose_name='点赞时间'),
        ),
        migrations.AlterField(
            model_name='tagzj',
            name='article_id',
            field=models.IntegerField(verbose_name='文章id'),
        ),
    ]
