# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-30 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190630_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wailian',
            options={'verbose_name': '为您推荐', 'verbose_name_plural': '为您推荐'},
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 18, 1, 2, 392035), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 18, 1, 2, 392068), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='attention',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 18, 1, 2, 395457), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 18, 1, 2, 394735), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liek',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 18, 1, 2, 396723), verbose_name='点赞时间'),
        ),
    ]
